### ISSUE TITLE
Strange test results

### ISSUE THREAD

**Issue by vielmath** [clojure-expectations/expectations#101]
I figured out that the test count in my summary was wrong.
I reproduced it with the following 2 lines example. 

```clojure
(let [a 5] (expect 2 a))
(let [a 2] (expect 2 a))
```
-> 
Ran 1 tests containing 1 assertions in 1 msecs
0 failures, 0 errors.

I may be doing it wrong bu this looks a bit strange...

**Comment by seancorfield** [comment]
Since `expect` generates a function, whose name is based on the hash of the body as I recall, your two `expect` forms are collapsing onto a single function (and the second one is overwriting the first one).

It's peculiarities like this, and lack of compatibility with `clojure.test`-based tooling, that led me to add `expectations.clojure.test` and use that approach -- user-named expectations -- instead. At work we've completely abandoned the unnamed `expect` approach.

In the original approach for Expectations, the `(expect ...)` forms are intended to always be top-level since they generate a `defn` behind the scenes. That may not be clear enough in the readme or docs -- I'd be happy to make updates if you have suggestions.

I really need to finish my overhaul of the documentation and complete the test reporting for `expectations.clojure.test` which will essentially deprecate the old approach in favor of the new one.

See https://clojure-expectations.github.io/clojure-test.html for what is documented so far.
