### ISSUE TITLE
`expect` inside a doseq doesn't work as expected

### ISSUE THREAD

**Issue by duelinmarkers** [clojure-expectations/expectations#69]
If you write an expectation like the following, you expect each case in `my-cases` to be checked.

```
(doseq [case my-cases]
  (expect (handle case))
```

But a single source occurrence of `expect` redefs the same var on each iteration, so at the end it only has the result of the last iteration to run.

Instead of expanding to a `def` with a var-name generated at macro-expansion time, I think expanding to a call to `clojure.core/intern` with a var-name generated at runtime could solve this. Unfortunately I don't have the cljs familiarity to implement this in a cross-platform way. For clj, `gensym` should work, but I assume from 01c6633 that `gensym` isn't cljs-friendly.

A more sweeping change (perhaps populating an atom instead of defining vars) might lead to a simpler result, but would touch a lot more code.

**Comment by ghl3** [comment]
Ran into a similar issue which essentially boils down to this:


    (let [x 10]
      (expect 20 x))
    (let [x 20]
      (expect 20 x))


When run, only one assertion statement is made (the last one) and the whole test passes.  I would have naively assumed that this would have resulted in two assertions running, the first failing and the second passing.  Essentially, the first "expect" is shadowed by the second, presumably because the form in the expect call is the same both times and therefore hashes to the same value and becomes the same function, as noted in the above comment.

This feels potentially dangerous (I was bit by it, leaving me quite confused for a while).  Ideally, this would work as I anticipated.  However, I know that expectations is of the philosophy that there should be only one assertion per test.  As an alternative, perhaps it could emit a warning or error out when re-defining an assertion that will shadow an existing assertion in the same namespace.

**Comment by jaycfields** [comment]
I haven't had time to look at this, but I'm not opposed to merging a PR if someone looks into a solution.

**Comment by seancorfield** [comment]
@duelinmarkers You might consider `from-each` to solve your problem:

    (expect true
      (from-each [case my-cases]
        (handle case)))

@ghl3 I agree this is problematic in certain edges. Providing named tests via #82 will be a reasonable way to address this in the general case. I would be wary of changing the hashed ID of generated tests. Right now, if you reload a test namespace, tests that haven't changed won't generate new symbols, and Expectations tooling can assumes that after running a test and removing the `^:expectation` metadata, that test will not get run again until the namespace is reloaded -- and that relies on reloading not generating (many) new symbols. Again #82 will solve that by side-stepping the hashed name generation completely, which will work better with tooling at large.

I'm going to close this and defer to `from-each` and/or named tests via #82.
