### ISSUE TITLE
Move Expectations tooling to a new organization (was Implement the clojure.test protocol)

### ISSUE THREAD

**Issue by bbatsov** [clojure-expectations/expectations#70]
Basically this would allow tools like `cider-test` to run expectations tests, which would benefit a lot of Clojure developers. More details - https://github.com/clojure-emacs/cider#using-cider-test-with-alternative-test-libraries and https://github.com/clojure-emacs/cider/issues/1606

**Comment by jaycfields** [comment]
I'm not going to have time to work on this for awhile, but I'd love to merge it if someone else wants to do a PR.

**Comment by seancorfield** [comment]
Updated link to that CIDER test information: http://cider.readthedocs.io/en/latest/running_tests/#using-cider-test-with-alternative-test-libraries

I'm going to try to find time to look at this "soon" since having a better CIDER integration could be very helpful to our workflow at World Singles.

**Comment by seancorfield** [comment]
I have a very rough proof of concept working locally but there are some nasty gotchas:

The main issue is that `(expect e a)` produces a "random" symbol name (based on a hash of the form itself): if you change the test namespace and reload it, old definitions hang around (and the changed tests get new symbol names). Expectations mitigates this by not running expectations that have `::run` metadata (which is added as each expectation completes, using Expectations custom `report` function). The "downside" is that you have to reload the test namespace, or re-evaluate the forms, to get those symbols back in play. The Emacs / REPL workflow we've adopted with Expectations is to evaluate either a single test or the whole namespace whenever we want to run them: this is kind of nice for working with tests as you write them but isn't an entirely smooth workflow overall.

If I make the CIDER integration follow that behavior, `C-c C-t r` doesn't work and neither do repeated `C-c C-t n` runs. You have to go back to the test namespace and reload it. If it doesn't follow that behavior, old tests just hang around and get re-run every time.

The other issue is that Expectations assumes a lot of context: when you run tests, you generally do it at the namespace level and it loads an `expectations-options` namespace, sets up `before-run` and `in-context` fixtures, watches for state changes etc, runs a set of tests and then tears it all down. As far as I can tell, working with CIDER test, there's no effective way to make this happen -- short of running `test-vars` for each `expect` form (i.e., for the `:test` function attached to the symbol it generates -- which will do all of the set up and tear down for each expectation).

My first approach was to do exactly that -- generate a function that ran `test-vars` and attach it as `:test` metadata but that is problematic due to setup/teardown (and it would need to rebind how the expectation reported its result which gets ugly pretty fast).

My second approach was to generate a function for `:test` that called a variant of `doexpect` that in turn called into `clojure.test/do-report` after mapping Expectations' `compare-expr` result data structure. This was much easier but loses `expectations-options` etc and still falls foul of the "random" symbol names.

I'm open to other suggestions but I think at this point the only option is to look into a syntax variant that provides fixed symbol names for expectations. This will alleviate the "random" symbol problem (and would make the existing Emacs / REPL workflow a lot smoother since expectations would no longer be "removed" as they are run, so you wouldn't need to reload the tests all the time).

If `clojure.test` compatibility -- and therefore CIDER test compatibility -- is handled via a separate namespace that relies on _named_ expectations, then much of this becomes much more tractable. Running `test-vars` on a per-symbol basis becomes much easier (even tho' it's still really the wrong way to do things) since the defined expectation function could call the `clojure.test/do-report` function instead of `expectations/report` and so on. This is going to be the path I go down next.

**Comment by jaycfields** [comment]
Hello all,
If we find a solution that works I'm all for merging it. I am starting to get a bit worried at a higher level though; I don't feel like the project has anyone with a good high level view. I don't use the cljs stuff, and have no idea if it's actually working or not. I'm on an old version of cider as well, so it's not likely I'll be using any of this anytime soon.

I'm wondering if it might be easier to simply write a new version of expectations from scratch. You could keep the same syntax and features, but rewrite the plumbing in a way that is more clojure idiomatic as well as supporting things like what this issue is about. I don't have the time or desire to do this, but people who are looking for expectations to keep evolving might, and I have no problem with that. I've got not issue with someone putting out a new expectations that retires my version, in fact I'd welcome it.

That said, if you (@seancorfield) or anyone else come up with a good solution here, I'm happy to merge it (as always).

Cheers, Jay

**Comment by seancorfield** [comment]
What might be nice would be to gather all the Expectations-related tooling under one banner -- an `expectations` organization in GitHub perhaps -- with the various Leiningen plugins, Boot tasks, and Emacs modes and so on, alongside the core Expectations library itself. I think that would help with maintenance and consistency. Perhaps migrate the documentation to http://expectations.github.io as well, and expand it.

I'm happy to act as steward since I'm pretty invested in it, but I'm also not too sure about the ClojureScript side of things (I ought to learn how deal with it since I maintain tools.cli which also has a ClojureScript version).

Regarding this particular issue of CIDER integration, I'm just not sure it can be made to work effectively without moving to a "named symbol" approach since so much of what CIDER (and the clojure.test infrastructure) assumes, is based around being able to run individual tests, so "the same syntax" would have to move a little, at least for folks who want that integration (and, FWIW, I do find naming tests, or groups of tests, to be useful from a documentation p.o.v.).

It could be as minimal as a wrapper that assigns a symbol name to one or more expectations:
```clj
(defx my-tests
  (expect e1 (some-expression v1))
  (expect e2 (some-expression v2)))
```
That would be the easiest syntax to migrate to (since you could wrap a whole namespace of expectations in a single `defx` to start with). Or it could be an additional `expect` form like this:
```clj
(expect-named my-test1 e1 (some-expression v1))
(expect-named my-test2 e2 (some-expression v2))
```
(the disadvantage is you'd need to explicitly edit and name every `expect` form in your current test suite for this).

**Comment by jaycfields** [comment]
Hey Sean, I'm 100% behind this. I don't think the plugins are really maintained anyway, and I highly doubt someone would object to you bringing everything together.

Also, I wouldn't worry about cljs support. I've never heard of a single person actually using expectations to test cljs for a production system.

**Comment by seancorfield** [comment]
Re: organization -- https://github.com/expectations is already taken (unfortunately) so we'd need a different (but still obvious name) if we do that. I should have checked before suggesting that. Suggestions?

I maintain https://github.com/seancorfield/boot-expectations, https://github.com/jakemcc/lein-autoexpect is maintained fairly actively by @jakemcc but https://github.com/gar3thjon3s/lein-expectations does not seem very active these days (@gar3thjon3s?) and the most recent commits are from Jay and myself. Tagging them to get a bit more feedback on this since implementing `clojure.test` style support will likely affect those tools too.

**Comment by jaycfields** [comment]
@jakemcc and @gar3thjon3s are friends of mine. I'm sure we can get their projects under an organization. How about clojure-expectations? It probably makes sense to language-space it anyway, as expectations does exist in other languages (ruby, emacs-lisp).

**Comment by seancorfield** [comment]
That works! I've created it and will invite y'all and we can begin to push this forward.

**Comment by seancorfield** [comment]
Moved: https://github.com/clojure-expectations/boot-expectations

**Comment by jakemcc** [comment]
Moved lein-autoexpect under the new organization. Thanks for setting it up.

**Comment by seancorfield** [comment]
Thanks @jakemcc -- clearly I did something wrong when I transferred ownership because I did not end up with a redirect like you did. What did I miss?

**Comment by jakemcc** [comment]
Hmm, not sure. I just transferred it using the transfer options under the project's settings.

**Comment by seancorfield** [comment]
@jaycfields @gar3thjon3s The clojure-expectations organization is set up and both boot-expectations and lein-autoexpect have moved there. Are we going to get Expectations itself (and its website?) and lein-expectations moved there as well? LMK if you need me to do anything with the organization to help make the move happens -- thanks!

**Comment by jaycfields** [comment]
sorry, yeah, I'll move expectations over now.

**Comment by gar3thjon3s** [comment]
Hi Sean, I tried to move lein-expectations but I don't have admin rights to clojure-expectations. You are a collaborator on lein-expectations - can you move it?

**Comment by gar3thjon3s** [comment]
Moved the lein-expectations repo over. Sorry, I didn't see your earlier question - I don't really have time for open source stuff these days so I'm happy to give over ownership of anything anyone wants to take. expectations-mode is also there, but I'm not sure anyone even uses that.

**Comment by seancorfield** [comment]
Thanks @gar3thjon3s -- I see lein-expectations there. I didn't see expectations-mode.

@jaycfields LMK if anything is blocking you in transferring ownership to clojure-expectations...

**Comment by jaycfields** [comment]
ownership of what? I moved expectations over, I think.

**Comment by jaycfields** [comment]
ah, I missed a click. Sorry. It's there now.

**Comment by seancorfield** [comment]
Yup, got it. Thanks. I created three teams and I think I added all the right folks to the right teams with the right permissions.

**Comment by gar3thjon3s** [comment]
transferred over expectations-mode too

**Comment by seancorfield** [comment]
Thanks @gar3thjon3s !

I copied expectations/gh-pages branch to clojure-expectations.github.io so we have a "standard" set of documentation https://clojure-expectations.github.io -- I'll delete that branch in due course. If there are gh-pages branches in the other repos or information in the wiki pages, we can think about organizing them under that documentation domain going forward.

If there are any issues any of you would like to raise against any of the newly moved repos, please go ahead.

Since this issue went off-topic pretty quickly, I'll rename it and close it, and then open a new one for the intended topic.

Thank you everyone for collaborating to move this forward -- much appreciated!

**Comment by seancorfield** [comment]
Now that we have everything moved over and a separate issue for addressing the `clojure.test` issue, I'm going to close this, as housekeeping. Over the next week or two I'll start up discussion on #82 and in the community to get input on how best to proceed.
