### ISSUE TITLE
clojure.test vs expectations -- tooling, maintenance, and deprecation

### ISSUE THREAD

**Issue by seancorfield** [clojure-expectations/expectations#96]
@jaycfields @jakemcc @gar3thjon3s

This recent issue on `expectations-mode` made me wonder if we need to chat about tooling and maintenance, in the context of `clojure.test` tooling vs the older Expectations-specific tooling: https://github.com/clojure-expectations/expectations-mode/issues/13

I see Jake has been updating `lein-autoexpect` recently, but `expectations-mode` hadn't been touched for nearly three years until I added the license information, `boot-expectations` hasn't been updated for over a year, `lein-expectations` hasn't been updated for two and a half years, and `simple-expectations` hasn't been updated for about three and a half years (aside from a recent README update).

Given the issues running traditional Expectations tests with CIDER and other tooling that relies on predictably named tests that can be run and re-run on demand, is there value in deprecating the old way of doing things and coalescing around the newer `clojure.test`-compatible approach, which is automatically supported by existing tooling -- thus lowering the maintenance burden on us?

I switched World Singles' code base from the unnamed Expectations to the named (`defexpect`) form so that we can leverage existing `clojure.test`-compatible tooling (`boot-test`, CIDER, ProtoREPL). I don't have a sense of what others are doing in that regard -- the #expectations channel on the Clojurians Slack is relatively quiet -- so it's hard to tell how many people still use Expectations at all let alone whether folks have switched to the new `defexpect` approach.

If folks are heavily attached to the traditional Expectations approach, that's fine too...

**Comment by mmower** [comment]
I've been using lein autoexpect from the command line fairly happily.
I use Cursive 100% of the time and am interested in its support (I think via the IntelliJ JUnit runner) but I couldn't figure out the instructions at a glance and the friction to my current solution wasn't sufficient to motivate me to figure it out.

**Comment by jaycfields** [comment]
I hate named expectations, so it's pretty obvious what my opinion is 😁. I'm fine living on an old version of expectations though. 

Introducing a large change, such as deprecating the most used part of the framework seems like it would upset people that have large test suites.

All that said, you're ( @seancorfield ) in charge, so I think it's really up to you. 😄

**Comment by jaycfields** [comment]
@mmower the JUnit runner is pretty old. I think it could be resurrected, but would require someone digging into it. I'm on emacs these days, but if I ever make the switch I'll circle back to see what you're up to.

**Comment by jaycfields** [comment]
@seancorfield one other thought... maybe I'm on an old version of cider or something, but I still run expectations in emacs and on the command line and both work great for me.

**Comment by kkinnear** [comment]
I've been perfectly happy with the classic expectations for several years, but since seeing Ambrose's talk at the conj a couple of weeks ago about auto-generating starter versions of function specs, I've been exploring converting to the clojure.test compatible version of expectations -- since his approach requires clojure.test tests.  

My initial attempt didn't work, as I tried to convert a single test with defexpect, and then some later expectations tests stopped working.  Then I tried wrapping all of the tests in a file, and that also didn't work because some of the setup that worked for the regular expectations tests seemed to stop working inside the defexpect.  I left it there for the present, expecting to come back and dig more deeply into what is going on when I have more time.

I expect that over time I will figure out how to migrate my tests to the clojure.test approach, even though two weeks ago I would have never imagined that I would be doing so.  Not having actually succeeded with migrating any of my tests, I don't know how I feel about what sounded like a loss of some of the expectations error reporting (which was what first drew me to expectations).

Ultimately, I am resigned to having to convert my tests to the clojure.test expectations approach in order to stop swimming against the current, and supportive of you all having less work to do maintaining alternative approaches to running expectations.

**Comment by jakemcc** [comment]
I only use expectations for a few projects and only use `lein-autoexpect` for running my tests. I'm still using the unnamed expectations on those projects. I wouldn't take my usage as usage that should actually drive what direction the project goes.

We should be careful with conflating activity on a repo for a projects use. There hasn't been a project changing commit for `lein-autoexpect` since mid 2016 but it still just works.

**Comment by seancorfield** [comment]
> We should be careful with conflating activity on a repo for a projects use.

Indeed. Many Clojure projects are very stable and haven't needed maintenance for a long time. I was mostly looking for either "We're happy using it as-is" or "We've stopped using it" responses, as confirmation that those projects really didn't _need_ additional maintenance.

> Introducing a large change, such as deprecating the most used part of the framework...

Deprecating things doesn't change anything. It's more about messaging. I have no plans to remove any features. The most noticeable change -- if I go down this path -- would be an overhaul of the documentation to be `clojure.test`-first: documenting `expectations.clojure.test` and `defexpect` up front (and showing they work out-of-the-box with Leiningen, with no plugins needed), and rewriting all the examples to use `defexpect`, with the unnamed form of `expect` as an option on each page. Then gathering up the information about unnamed Expectations tooling into its own page (rather than the current approach where `clojure.test` is its own page).

@mmower I'd certainly be keen to see Expectations supported by Cursive so I'll talk to Colin about what might be needed there (it may be that the `clojure.test`-compatible approach to Expectations would "just work" but if it requires JUnit supported then that definitely needs to be brought up to date).

@kkinnear I'm happy to help with your migration to the `clojure.test`-compatible approach. Feel free to either open issues here or reach out directly via email or via DM on the Clojurians Slack (or in the `#expectations` channel there).

**Comment by seancorfield** [comment]
@mmower I spent some time working with Cursive (and bugging Colin) and I can report that Expectations 2.2.0-rc3, using `expectations.clojure.test` (named tests), works pretty well out-of-the-box with Cursive now. Colin is going to add direct support for the `defexpect` macro which should be the final piece of that puzzle.

See https://github.com/seancorfield/cursive-expectations for a minimal test project demonstrating that. Running the IntelliJ REPL and using `REPL > Runs tests in current NS in REPL` will report test passes and failures directly in the source editor with 2.2.0-rc3! You can also create a run configuration for `lein test` and execute Expectations tests that.

**Comment by Skinney** [comment]
I'm fine with expectations as-is. I've no need, nor have the thought crossed my mind, of using named expectations or any form of clojure.test integration at all.

I'm using both Cider and lein-autoexpect and loving it.

**Comment by seancorfield** [comment]
After a lot of thought, experimentation, and day-to-day work experience with the `clojure.test` compatibility layer, I have decided to "reset" Expectations (and its documentation) to its former self, with the addition of `approximately` and `functionally` and will continue to evolve the "classic" testing library accordingly.

The `clojure.test` compatibility has been rewritten completely in a separate library [expectations/clojure-test](https://github.com/clojure-expectations/clojure-test) and will track changes to "classic" Expectations but also evolve completely independently (it has no dependencies on anything except `clojure.test` itself now). An initial release of that will be cut in due course.

Thank you, everyone, for all your input on this!
